### ISSUE TITLE
Wildcard world name

### ISSUE THREAD

**Issue by chelminski** [LoneDev6/Wiki-ServerBooster#1]
Hi ;)
I'm using your plugin, but I have a little problem. On my server, players can create their own worlds. In general, everything is changing quite dynamically. In your plugin, I am forced to indicate specific worlds for optimization. Could you solve my problem and make it so that plugin to optimize all ('*') worlds?

Thank you in advance!

**Comment by LoneDev6** [comment]
You can use "ALL", it should work.
Please let me know.
Anyway in the next update I will add the * wildcard support so that you can do that, similarly on how it works in some of my other plugins, for example in [ItemsAdder](https://itemsadder.devs.beer/plugin-usage/adding-content/huds#enable-in-all-worlds-of-name-which-starts-with-world_-or-adventure).

**Comment by LoneDev6** [comment]
Anyway i moved your issue report on the correct repository.

https://github.com/PluginBugs/Issues-ServerBooster/issues/95
